insert into worker( name_worker, birthday, level_skill,salary) values('Oliver','1988-04-01','Trainee',450);
insert into worker( name_worker, birthday, level_skill,salary) values('Jack','1989-03-02','Junior',1200);
insert into worker(name_worker, birthday, level_skill,salary) values('Harry','1991-01-03','Middle',2500);
insert into worker( name_worker, birthday, level_skill,salary) values('Jacob ','2000-02-04','Senior',6300);
insert into worker( name_worker, birthday, level_skill,salary) values('Charley','2001-01-05','Junior',1000);
insert into worker( name_worker, birthday, level_skill,salary) values('Thomas','2002-12-06','Middle',2300);
insert into worker(name_worker, birthday, level_skill,salary) values('George','2003-11-07','Senior',6500);
insert into worker(name_worker, birthday, level_skill,salary) values('Oscar','2004-10-08','Junior',1100);
insert into worker( name_worker, birthday, level_skill,salary) values('Emma','2005-09-09','Middle',2400);
insert into worker( name_worker, birthday, level_skill,salary) values('Olivia','2006-01-11','Trainee',450);
insert into worker( name_worker, birthday, level_skill,salary) values('Ava','1988-06-12','Juniore',1000);
insert into worker(name_worker, birthday, level_skill,salary) values('Sofia','1988-05-13','Middle',2200);
insert into worker( name_worker, birthday, level_skill,salary) values('Isabel','1988-04-14','Senior',7000);

insert into client (name) values ('James');
insert into client (name) values ('John');
insert into client (name) values ('Robert');
insert into client (name) values ('Michael');
insert into client (name) values ('William');
insert into client (name) values ('Mary');
insert into client (name) values ('Jennifer');
insert into client (name) values ('Linda');
insert into client (name) values ('Jessica');

insert into project( start_date, finish_date, client_id) values('2022-11-30','2022-12-30',1);
insert into project( start_date, finish_date, client_id) values('2023-01-03','2023-03-06',2);
insert into project( start_date, finish_date, client_id) values('2023-01-15','2023-06-01',3);
insert into project( start_date, finish_date, client_id) values('2015-01-15','2023-01-04',4);
insert into project( start_date, finish_date, client_id) values('2022-01-17','2023-02-06',5);
insert into project( start_date, finish_date, client_id) values('2020-04-08','2022-12-15',6);
insert into project( start_date, finish_date, client_id) values('2019-06-17','2022-05-09',7);
insert into project( start_date, finish_date, client_id) values('2019-10-17','2023-01-26',8);
insert into project( start_date, finish_date, client_id) values('2016-07-19','2022-09-23',9);
insert into project( start_date, finish_date, client_id) values('2016-07-15','2016-10-02',1);
insert into project( start_date, finish_date, client_id) values('2017-09-14','2022-11-14',2);

insert into project_worker(project_id,worker_id ) value(1,1);
insert into project_worker(project_id,worker_id ) value(1,2);
insert into project_worker(project_id,worker_id ) value(1,3);
insert into project_worker(project_id,worker_id ) value(2,4);
insert into project_worker(project_id,worker_id ) value(2,5);
insert into project_worker(project_id,worker_id ) value(2,6);
insert into project_worker(project_id,worker_id ) value(2,7);
insert into project_worker(project_id,worker_id ) value(3,8);
insert into project_worker(project_id,worker_id ) value(4,9);
insert into project_worker(project_id,worker_id ) value(4,10);
insert into project_worker(project_id,worker_id ) value(4,11);
insert into project_worker(project_id,worker_id ) value(4,12);
insert into project_worker(project_id,worker_id ) value(5,13);
insert into project_worker(project_id,worker_id ) value(6,13);
insert into project_worker(project_id,worker_id ) value(6,1);
insert into project_worker(project_id,worker_id ) value(7,2);
insert into project_worker(project_id,worker_id ) value(8,3);
insert into project_worker(project_id,worker_id ) value(9,4);
insert into project_worker(project_id,worker_id ) value(10,5);
insert into project_worker(project_id,worker_id ) value(10,6);
insert into project_worker(project_id,worker_id ) value(11,7);
insert into project_worker(project_id,worker_id ) value(11,8);